### ISSUE TITLE
Epic: API Bugs Tracking

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/data-node#12]
In order to continue to collate and track the non-critical API bugs (those not prioritised for current/next sprint) we will use this EPIc to collate and track the issues.

**Bugs should only be added into this list once they have been triaged and deemed a bug we are OK to have in the protocol for longer than 1 or 2 sprints - this allows us to track the bugs of this type of priority**

- [ ] vegaprotocol/vega#5721 (Bug Low)
- [ ] vegaprotocol/data-node#13 (Bug Medium)
- [ ] vegaprotocol/vega#5697 (Bug Low)
- [ ] vegaprotocol/data-node#15 (Bug Low)
- [ ] vegaprotocol/protos#478 (Bug Medium)
- [ ] vegaprotocol/data-node#17 (Bug Medium)
- [ ] vegaprotocol/data-node#18 (Bug Medium)
- [ ] vegaprotocol/data-node#19 (Bug Medium)
- [ ] vegaprotocol/data-node#20 (Bug Medium)

Each bug may require further triage, refining and prioritising.
