### ISSUE TITLE
Epic: API improvements (post API split)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/data-node#22]
In order to continue to improve the API after the API split refactoring we may want to implement a number of API improvements.

This Issue is an epic where we can capture the list of improvements. Each improvement may require refining and prioritising.

## Vega Repo:
- [x] vegaprotocol/vega#3786
- [ ] vegaprotocol/vega#2277
- [ ] vegaprotocol/vega#1797  **Move to data-node repo? - linked vega PR**
- [x] vegaprotocol/vega#1683  **Move to data-node repo? - linked vega PR**
- [ ] vegaprotocol/vega#1617  (Duplicated as vegaprotocol/vega#2228)
- [ ] vegaprotocol/vega#773
- [ ] vegaprotocol/vega#769
- [ ] vegaprotocol/vega#745 

## Data-Node Repo:
- [x] vegaprotocol/data-node#23
- [x] vegaprotocol/data-node#24
- [ ] vegaprotocol/data-node#25
- [x] vegaprotocol/vega#5723
- [x] vegaprotocol/data-node#27
- [x] vegaprotocol/data-node#28
- [x] vegaprotocol/data-node#29
- [x] vegaprotocol/data-node#30
- [x] vegaprotocol/data-node#31
- [x] vegaprotocol/data-node#32
- [x] vegaprotocol/data-node#33
- [x] vegaprotocol/vega#5727
- [ ] vegaprotocol/vega#5728
- [x] vegaprotocol/vega#5729
- [x] vegaprotocol/vega#5730
- [x] vegaprotocol/vega#5735
- [x] vegaprotocol/data-node#43
- [x] vegaprotocol/data-node#44
- [x] vegaprotocol/data-node#45

NOTE: This and the linked issues may need to be transferred to the data-node repo issues list
