### ISSUE TITLE
Implement DataNode

### ISSUE THREAD

**Issue by cityhunteur** [vegaprotocol/data-node#3]
# Feature Overview

[Spec](https://github.com/vegaprotocol/specs/blob/master/non-protocol-specs/0003-api-node.md)

As a Vega network operator

I want to be able to operate a `DataNode` (API only node)

So I can deploy and scale out the API nodes independently of the Validator/Non-Validator nodes. 

# Tasks

- [x] Create a new repo based on existing `vega` repo to build binary for DataNode
- [x] Remove core functionality (engines) from `DataNode`
- [ ] Tests related to core functionality
- [x] Remove unused binary commands from `DataNode`
- [x] Remove any interaction with `Tendermint`
- [x] Move API tests to `DataNode` repo
- [x] Add configuration to connect to `Streaming Node`
- [x] Refactor event broker to use socket streams between publisher and subscriber (instead of Go channels)
- [x] Extend event broker to buffer events to handle delayed start of `DataNode`
- [x] Refactor `Gateway` to only keep service APIs, stats, monitoring and `SubmitTransaction` endpoints
- [x] Refactor `SubmitTransaction` API request to proxy request to `Streaming Node`

# Product Owner

Core development

# Acceptance Criteria

- Ability to develop, build and deploy DataNode from new repository 
- Ability to start the `DataNode` within a few (60?) seconds delay after starting the `Streaming Node`
- `DataNode` must tolerate transient network and connection issues to `Streaming Node`
- `DataNode` must process events received from `Streaming Node` in sequential order
- All services and corresponding APIs works as expected
- `DataNode` must not interact with `Tendermint`

# Test Scenarios

- All existing system tests pass
- All existing API tests pass

# Impacted Systems / Engines / Services

The following components shared between the `DataNode` and the Validator and Streaming (Non-Validator) Node:

- Event Broker
- Stats 
- Monitoring                 

The following services will be migrated to the `DataNode`

- Order Service
- Trade Service
- Candle Service
- Market Service
- Party Service
- Accounts Service
- Risk Service
- Notary Service
- Transfer Service
- GovernanceData Service
- Asset Service
- Fee Service
- Withdrawal Service
- Deposit Service
- NetParams Service
- Liquidity Service
- Oracle Service

# Dependencies
