### ISSUE TITLE
Pick SQL migration library, set up a minimal working SQL environment

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#305]
# Feature Overview

## Decide on migration tool

When starting with a blank database, we need to make create all the various tables and indexes.

When the schema changes in future versions of datanode, we need to update existing databases.

I've done a little research and there are two that keep popping up

[goose](https://github.com/pressly/goose#embedded-sql-migrations) and [golang-migrate](https://github.com/golang-migrate/migrate). There doesn't seem to be a whole world of difference but if anyone has used them before it would be nice to hear horror/success stories.

The general gist seems to be that you have a bunch of .sql scripts called _migrations_, which you apply in order, and keep track of what number you are up to. 

I think a must have is the ability to embed the migrations into the binary so we don’t have to ship a separate bunch of .sql scripts.

TBD: When bringing up a data node, should we automatically bring the database schema up to the latest version, or ask user to manage it with CLI commands?

**As a** developer
**I want** to be able to make changes to the database schema, and apply those changes to my own database as well as other users once they start using code that has my changes in it.
**So that** We don't need to replay the entire block chain and fill a database from scratch for every new feature.

## Discussion

[design doc](https://www.notion.so/vegaprotocol/Data-Node-V2-277767dd3a144be4b58c622051cade74)

# Tasks

- [ ] Do a bit of research, pick a nice go sql migration library
- [ ] Write some code so that on startup, we connect to a DB defined in the config file
- [ ] Check what schema version it is, and upgrade if necessary
- [ ] A command line argument to start a fresh database at start-up (in fact this should possibly be the default for now) 

# Notes

Something we might have to be wary of is if two developers are working on a branch and both add a change containing a migration. 

With whatever ordering scheme we choose, one of them will be considered the latest - and when that developer pulls changes from the other, and the migration tool might well just ignore the changes from the migration that appears not to be the latest one.

It might be possible to keep track of each individual migration that has been applied rather than the latest one, which works as long as it doesn't make any difference in which order they are applied.

In any case this is possibly a problem for quite a way down the line as for as long as we have any state that isn't in the database we'll continue to need to play the whole chain at start up.

# Acceptance Criteria

- [ ] We have a couple of SQL migrations written to create tables for assets, accounts etc..
- [ ] When I start data node with a configured database, the schema is bought up-to date
- [ ] Initially, by default the database is wiped at start up
- [ ] We have a command line option for that not to occur, maybe, say, `--database-init={wipe|continue}`

# Test Scenarios
TODO: Detailed scenarios (1-3!) that can be executed as feature tests to verify that the feature has been implemented as expected. We use the follow format:

GIVEN (setup/context) 

WHEN (action) 

THEN (assertion)
