### ISSUE TITLE
Add API for querying transfers

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#306]
# Feature Overview

**As a** Front end developer 
**I want** I want to be able to query historical transfers
**So that** We can show users where their assets came from / went

## Specs

- [Design Discussion](https://www.notion.so/vegaprotocol/GraphQL-API-774b19b5f68840b99d374ef725462b19)

# Tasks
- [x] Confirm with TFE team that what the API should look like 
>  Happy with it though what they really want is a few steps on from this ]
- [x] Figure out if we're going to start using cursors for pagination instead of (skip, first, last) 
>  No, not yet
- [ ] Write the go service that can answer the queries we want
- [ ] Add the grpc wrapper for that service
- [ ] Write graphql schema
- [ ] Write resolver that fetches query by talking to GRPC api 

# Dependencies
Needs a working database & grpc api first; this ticket is here initially for planning and to firm up the API.
