### ISSUE TITLE
Initial database setup

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#307]
# Feature Overview
Get the datanode optionally (for now) talking to a postgres database that is specified in it's config file. 

**As a** developer
**I want** to start using a database
**So that** we can make data node awesome

# Tasks
- [ ] Add configuration options for database host/port/database
- [ ] Add configuration for enabling connection
- [ ] Add some code for connecting and getting a handle to that database if the above option is set
- [ ] If the database _is_ enabled, add some extra event stream listers (a dummy one will suffice for now) that gets the connection details.

# Acceptance Criteria

- It is possible to: have a dummy sql store module that initialises at startup and talks to an empty database
