### ISSUE TITLE
Get embedded postgres working

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#310]
# Feature Overview

It would be great if e.g. for testing and also for validators getting set up quickly if they didn’t have to faff around starting an postgres instance, creating a database & account etc..

This project:

[https://github.com/fergusstrange/embedded-postgres](embeddeed postgres)

Enables that by providing a go library that goes and downloads an appropriate version of postgres, unpacking it in a private directory, firing it up and shutting it down.  It uses binaries built by this project

[https://github.com/zonkyio/embedded-postgres-binaries](https://github.com/zonkyio/embedded-postgres-binaries)

Which was built for solving this problem, but in Java, so it uses `gradle` to build it for a whole bunch of architectures and platforms and uploads the binaries into some Maven repository.

I think we want to fork embedded-postgres-binaries, add in timescale (I’ve already done this for Linux, it works a bit differently on MacOS), and probably host our own set of binaries so we aren’t vulnerable to someone taking it down at some point.

Then we can depend on a fork of embedded-postgres-go that looks at our repo. It also currently launches postgres using pg_ctrl which runs it *daemon mode,* detached from the parent process which means that postgres won’t be killed if the parent process dies (embedded-postgres-go gives you a function to gracefully shut it down). I think we should run it as a normal subprocess by launching `postgres`directly.

# Tasks
A checklist of the tasks that are needed to develop the feature and meet the accceptance criteria and feature test scenarios. Ideally, tasks would reflect the pull requests likely to be created when developing the feature. 

- [x] Fork embedded-postgres-binaries, get timescale building with it   (I have code for doing this on linux, on MacOS it doesn't build from source, could be a bit more faffy)
- [x] Figure out how to upload those binaries to our own repo somewhere
- [x] Fork embedded-postgres-go to point at our repo
- [ ] Maybe offer changes back upstream
