### ISSUE TITLE
Add ability to run a data node being fed a stored event stream

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#315]
# Feature Overview
When developing the data node, it's a bit of a faff to have to spin up a core node, tendermint etc.. and connect to a blockchain and wait for the sort of events you are interested to come down the pipe.

It would be very useful to start the data node and instead read from a file containing either a protobuf or json stream of events.

This will also be useful for an integration test.

**As a** data node developer
**I want** to be able to read a saved of bus events
**So that** I can quickly iterate and test my coode

# Tasks
- [ ] Write a tool for dumping event stream data (maybe we can use vegatools stream to begin with)
- [ ] Add configuration options to data node to specify a file instead of a host:port of a core node
- [ ] Write some code to ingest that file and push it onto the event bus.
