### ISSUE TITLE
Add account balances to database

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#327]
**As a** front end developer
**I want** to be able to show users' balances over time
**So that** they can understand where all their money has gone

[[Link](https://www.notion.so/vegaprotocol/Data-node-Core-API-Requirements-e8d00fbd0c96425687bfa0bc00baf8eb)](notion page with FE requirements)

# Tasks

- [x] Decide if we're going to compute ourselves from the ledger, or just record balances provided by core
- [x] Design db schema
- [x] Write storage layer
- [x] Write code to populate storage layer
- [ ] Add API that makes it possible to query 

# Acceptance Criteria

API exists to query:
- [ ] Margin balance for a party over time
- [ ] General account balance for a party over time
- [ ] Amount of any Asset on Vega right now (broken down by account type)
- [ ] Fees I've received/paid (current balances and historical)
- [ ] Asset balance (whole of Vega) over time + broken down by account type
