### ISSUE TITLE
Add orders to database

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#328]
# Feature Overview

**As a** user of Vega
**I want** to be able to query historical orders
**So that** I can audit my PnL, design trading strategies, etc..

I believe we already keep this data in badger db, so hopefully we can keep the same API

There is also a core [ticket](https://github.com/vegaprotocol/vega/issues/4567) for having deterministic order ids so that clients can follow orders once submitted to the chain. That's slightly orthogonal to this but worth bearing in mind.

# Tasks

- [ ] Design schema
- [ ] Write storage layer
- [ ] Write an event bus subscriber that populates the storage layer
- [ ] Write / implement API for querying

The FE wishlist includes an item 
- 'Aggregation (instead of tick size e.g. 0.00001 we'd like the data back aggregated in 0.001 blobs'

Understand exactly what they mean by that and add it to the API
