### ISSUE TITLE
Add Trades to database

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#329]
# Feature Overview
Store all trades that have occurred in the database

**As a** user of vega
**I want** to see historical trades
**So that** I can audit my pnl, design trading strategies etc..

# Tasks

- [ ] Design a schema
- [ ] Write a storage layer
- [ ] Write an event bus subscriber that listens for trade events and populates
- [ ] Write an API that mirrors the current badger-db based one
- [ ] Maybe see what new stuff we can do with aggregation (e.g. daily summaries?), check with TFE to see if that's useful.
