### ISSUE TITLE
Store market data in the database

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/data-node#330]
# Feature Overview

**As a** user of vega
**I want** to get current and historical market data
**So that** I can design trading strategies, look at charts etc..

This is the tip of a larger iceberg, but a good start will be to put each 'MarketData' event from each into the database and provide some API for querying it at various timescales.

As far as I can tell the current API only allows us to retrieve current market data for a particular market; we want to extend this to get an arbitrary range, or aggregations of that range.

## Specs

- [https://github.com/vegaprotocol/specs-internal/pull/763/files](https://github.com/vegaprotocol/specs-internal/pull/763/files) 

# Tasks

- [x] Understand the shape of the data and design a schema for it
- [x] Write the storage API for inserting that
- [x] Write a market data subscriber for populating it
- [x] Implement the existing simple api 'current market data for this market'
- [x] Design/implement an api for getting a range of market data
- [ ] Figure out if/what would be useful to return in aggregate and write some API for that (e.g. hourly summary)
