### ISSUE TITLE
Tidyup legacy instructions inherited from vegaprotocol/vega

### ISSUE THREAD

**Issue by edd** [vegaprotocol/data-node#396]
I was trying to run [vegaprotocol/vegacapsule](https://github.com/vegaprotocol/vegacapsule), and to do so needed data-node to be built and installed on my path. I failed at this for two reasons:

- There is a makefile that I don't believe is used by anyone, that used a command a don't have
- I did not know that `go build ./cmd/data-node` and `go install ./cmd/data-node` were the commands I needed to run. `go build` alone does not work

I'm not a go dev, so maybe those things are clear to everyone who is, but if vegacapsule is going to be a nice easy tool, let's make all the parts of it nice and easy. Which means making building this project straightforward. Luckily, that's going to be easy:

# Tasks
- [ ] Ensure no-one is using the makefile
- [ ] If the are, remove the bits that are not used and put a warning in the makefile
- [ ] If they aren't, delete the makefile
- [ ] Update the README with build instructions

**Comment by gordsport** [comment]
Closing as datanode is moving back to vega repo - instructions will be updated there
