### ISSUE TITLE
API Split - node version handshake

### ISSUE THREAD

**Issue by cityhunteur** [vegaprotocol/data-node#63]
# Feature Overview

Implement a basic handshake with `core` nodes to ensure it is at the expected version so events received by the data-node over the socket stream are compatible.

Relates to https://github.com/vegaprotocol/vega/issues/3474

# Tasks

- [ ] Create proto for `NodeInfo` 
- [ ] Add handshake logic on new connection to socket
- [ ] Check first message from socket corresponds to `NodeInfo` and has expected version

# Acceptance Criteria

- Receive events after successful handshake
- Disconnect from `core` node if version does not match

# Test Scenarios

# Impacted Systems / Engines

- core
- data-node
