### ISSUE TITLE
Add 24 hour volume to Market data

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/data-node#737]
# Feature Overview

As a trader I would like to know how much trading has happened in the last 24 hours on a given market as a gauge of it's activity/popularity etc.

```GraphQL
markets {
  data {
    24hourVol
  }
}
```
the `24hourVol` is just a suggestion, not sure it is okay to start with a number

## Specs
Technically it isn't in the [Market data](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0021-MDAT-market_data_spec.md) spec at time of writing. 
But the idea got the nod and here is a [ticket to add it to the spec](https://github.com/vegaprotocol/specs-internal/issues/1129).

# Tasks
- [ ] Agree the frequency that this updates
- [ ] Agree the name
- [ ] Add it to the API
- [ ] see discussion on ticket or detail spec for what should happen in the first 24 hours
- [ ] Comment on this [ticket](https://github.com/vegaprotocol/frontend-monorepo/issues/625) to let FE know it is done 

# Acceptance Criteria
A list of criteria (aim for 3!) that have to be met for this feature to be accepted as 'done' by the product owner.

- There is a relatively real time value representing the amount of contracts traded in the last 24 hours on the markets.data query
- Show the same number of decimal places as position decimals
- this is available via subscription as well as a query

# Test Scenarios
I suggest using the same tests/format that exist for open interest

# Additional Details (optional)
note [this](https://github.com/vegaprotocol/data-node/issues/537) is also for general trades history API but **this** was deemed to be a separate task

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature
