### ISSUE TITLE
Add Rewards API to DataNode

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/data-node#76]
# Feature Overview
As an API user of VEGA we wish to be able to query the total amount of reward a party has received so that we can display that information to the clients via the console.

## Specs
- [Rewards for Sweetwater](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0056-rewards-overview.md#-sweetwater)

# Tasks
- [x] Build a subscriber/plugin in the DataNode that takes TRANSFER_REWARD events and keeps a running total for each party along with the last transfer size and assetID
- [x] Add support to query that subscriber/plugin to get the reward total, last transfer and assetID for a given partyID
- [x] Add gRPC API support for querying the running totals, last transfer size and assetID by partyID
- [x] Add GraphQL and RestAPI support for the same data

# Product Owner
Core

# Acceptance Criteria
- It is possible to query the DataNode to get the current amount of rewards a party has received during the network life along with the last transfer size and assetID.
- It is possible to query using gRPC, GraphQL and RestAPI
- The values should be updated after each reward distribution

# Test Scenarios
- Request reward information for a partyID that does not exist. Receive an empty message.
- Request reward information for a partyID that has received no rewards. Receive an empty message.
- Request reward information for a partyID that has received rewards. Receive a message with the total amount of rewards received so far and the last transfer size and assetID.

# Impacted Systems / Engines
- Core - subscribers
- API

# API Calls 
- Get reward details for a party
