### ISSUE TITLE
Implement a checkpoint API

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/data-node#88]
This is a very simple API, meant to expose all hashes of checkpoints created by nodes at first.
We'll want to expose these through the grpc, graphql and REST api.

```
rpc Checkpoints(CheckpointsRequest) returns (CheckpointResponses)

message CheckpointData {
  string hash = 1;
  uint64 at_block = 2;
  // in the future we can image the actual payload of the checkpoint or something
  // for now the hash only is fine.
}

message CheckpointsRequest {
  // nothing in there for now for sweetwater, in the future we can imagine having filters for the data (hash, data, or all), and limits (last 50, etc).
}

message CheckpointsResponse {
  repeated CheckpointData = 1;
}
```

A similar GraphQL APi is expected.

### Tasks
- [ ] Build the grpc endpoint
- [ ] Build the rest endpoint
- [ ] Build the graphQL endpoint.
